all : bin-noerr modshift jktebop jktld

bin-noerr :
	g++ -Wno-unused-result -O3 -o bin-noerr bin-noerr.cpp

modshift :
	g++ -Wno-unused-result -O3 -o modshift modshift-dave.cpp

jktebop :
	gfortran -O3 -o jktebop jktebop-dave.f

jktld :
	gfortran -O3 -o jktld jktld-v3.f

